services:

  front:
    image: nginx:alpine
    ports:
      - 8334:80
    volumes:
      - ./front:/usr/share/nginx/html:ro
    networks:
      - front-network

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pwd
      WORDPRESS_DB_NAME: mydb
    networks:
      - db-network
      - front-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql # Utilisation du volume nommé
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - db-network

volumes:
  db_data: # Déclaration du volume nommé

networks:
  db-network:
  front-network: