services:
  front:
    build: ./front
    ports:
      - 5173:5173
    volumes:
      - ./front:/app
      - /app/node_modules  #volume anonyme pour separer le volume du conteneur et des node_modules et garder la persistance des données
   

